apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-cinder-iscsi-node-sa
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cinder-iscsi-nodeplugin-role
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cinder-iscsi-nodeplugin-binding
subjects:
  - kind: ServiceAccount
    name: csi-cinder-iscsi-node-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-cinder-iscsi-nodeplugin-role
  apiGroup: rbac.authorization.k8s.io
