{{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  {{- if .Values.storageClass.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
  labels:
    {{- include "cinder-iscsi-csi.labels" . | nindent 4 }}
provisioner: cinder-iscsi.csi.windriver.com
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{- if .Values.storageClass.parameters }}
parameters:
  {{- toYaml .Values.storageClass.parameters | nindent 2 }}
{{- end }}
{{- end }}
